apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30081
    name: jtq-backend-port
  - port: 80
    nodePort: 30800
    name: jtq-frontend-port
  selector:
    app: webapp