apiVersion: v1
kind: Service
metadata:
  name: jtq-nodeport
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 31111
    protocol: TCP
    name: jtq-backend
  - port: 81
    targetPort: 4200
    nodePort: 31112
    protocol: TCP
    name: jtq-frontend
