name: Build And Analyse Frontend
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - name: Setup Angular CLI
        uses: mayurrawte/github-angular-actions@latest
      - name: Setup Yarn
        uses: CultureHQ/actions-yarn@v1.0.1
      - name: Build frontend
        working-directory: ./angular
        run: |
          yarn install
          ng build
      - name: Analyse frontend
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
