name: Build and Push Docker Images
on:
  repository_dispatch:
    types: [trigger-next-workflow]

jobs:
  build_and_push_docker_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: mmj21
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build And Push Backend
        working-directory: ./java/jtqj
        run: |
          docker build -t mmj21/repo:jtq-backend-1.0 .
          docker push mmj21/repo:jtq-backend-1.0
      - name: Docker Build And Push Frontend
        working-directory: ./angular
        run: |
          docker build -t mmj21/repo:jtq-frontend-1.0 .
          docker push mmj21/repo:jtq-frontend-1.0
          
        
      
      
